### ISSUE TITLE
DotWriter only works for OBO-type PURLs

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/kboom#1]
see bad assumption here: 

https://github.com/monarch-initiative/kboom/blob/master/boom-core/src/main/java/org/monarchinitiative/boom/io/CliqueSolutionDotWriter.java#L229-L231

**Comment by cmungall** [comment]
In some cases, fragment may be empty.

**Comment by wdduncan** [comment]
I am getting an error when I run the command:
```
kboom --experimental  --splitSize 50 --max 8 -m rpt.md -j rpt.json -n -o test-axioms.ow -t probs.tsv slim-exposure.owl
```
Is this related?

Here is the complete error:
```
java.io.IOException: Cannot run program "/opt/local/bin/dot": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:589)
	at java.base/java.lang.Runtime.exec(Runtime.java:413)
	at java.base/java.lang.Runtime.exec(Runtime.java:310)
	at org.monarchinitiative.boom.io.CliqueSolutionDotWriter.renderToFile(CliqueSolutionDotWriter.java:75)
	at org.monarchinitiative.boom.runner.MarkdownRunner.render(MarkdownRunner.java:75)
	at org.monarchinitiative.boom.runner.MarkdownRunner.lambda$render$0(MarkdownRunner.java:68)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1605)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.monarchinitiative.boom.runner.MarkdownRunner.render(MarkdownRunner.java:68)
	at org.monarchinitiative.boom.runner.RunEngine.run(RunEngine.java:124)
	at org.monarchinitiative.boom.runner.RunEngine.main(RunEngine.java:80)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:250)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 17 more
```
